# Generated by Django 4.0.7 on 2022-12-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('you', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='img',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='link',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
