# Generated by Django 4.0.7 on 2022-12-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='img',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
