# Generated by Django 4.0.7 on 2022-12-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0003_alter_blogdata_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='img',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
