# Generated by Django 4.0.7 on 2022-12-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_owner_alter_post_create_dt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, help_text='simple description text', max_length=500, verbose_name='DESCRIPTION'),
        ),
    ]
